# Generated by Django 2.2.1 on 2019-06-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
