# Generated by Django 2.2.1 on 2019-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
