# Generated by Django 2.2.1 on 2019-06-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='detail',
        ),
    ]
