# Generated by Django 2.2.1 on 2019-08-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('drink', 'Drink'), ('food', 'Bakery')], max_length=20)),
                ('menu_category', models.CharField(max_length=20)),
                ('drink_type', models.CharField(blank=True, choices=[('IC', 'Iced'), ('HO', 'Hot')], max_length=10, null=True)),
                ('drink_size', models.CharField(blank=True, choices=[('SM', 'Small'), ('TA', 'Tall'), ('GR', 'Grande'), ('VE', 'Venti')], max_length=10, null=True)),
                ('price', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
