# Generated by Django 2.2.1 on 2019-06-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('DR', 'Drink'), ('IC', 'Ice Cream'), ('SW', 'Sandwich'), ('BK', 'Bakery')], max_length=20)),
                ('drink_type', models.CharField(choices=[('IC', 'Iced'), ('HO', 'Hot')], max_length=10, null=True)),
                ('price', models.CharField(max_length=50)),
                ('drink_size', models.CharField(choices=[('SM', 'Small'), ('TA', 'Tall'), ('GR', 'Grande'), ('VE', 'Venti')], max_length=10, null=True)),
                ('takeout', models.CharField(choices=[('EI', 'Eat In'), ('TO', 'Take Out')], max_length=10)),
                ('detail', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
