# Generated by Django 2.2.1 on 2019-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='takeout',
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='drink_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('TA', 'Tall'), ('GR', 'Grande'), ('VE', 'Venti')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='drink_type',
            field=models.CharField(blank=True, choices=[('IC', 'Iced'), ('HO', 'Hot')], max_length=10, null=True),
        ),
    ]
