# Generated by Django 2.2.1 on 2019-09-30 11:05

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190806_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/product/', verbose_name='Image'),
        ),
    ]
