# Generated by Django 2.2.1 on 2019-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_detail'),
        ('product', '0002_auto_20190613_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='Product_favorite', to='customer.Customer'),
        ),
    ]
