# Generated by Django 2.2.1 on 2019-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('detail_address', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
