# Generated by Django 2.2.1 on 2019-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_detail'),
        ('supplier', '0002_auto_20190614_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='customer.Customer'),
        ),
    ]
