# Generated by Django 2.2.1 on 2019-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='Supplier_favorite', to='customer.Customer'),
        ),
    ]
