# Generated by Django 2.2.1 on 2019-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
        ('supplier', '0003_auto_20190822_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='supplier_product', to='product.Product'),
        ),
    ]
