# Generated by Django 2.2.1 on 2019-06-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('is_supplier', models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('CUSTOMER', 'CUSTOMER')], max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
