# Generated by Django 2.2.1 on 2019-06-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_drink', models.PositiveIntegerField(max_length=5)),
                ('normal_drink', models.PositiveIntegerField(max_length=5)),
                ('user_number', models.PositiveIntegerField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'users_frequencies',
            },
        ),
    ]
