# Generated by Django 2.2.1 on 2019-08-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_supplier',
        ),
    ]
