# Generated by Django 2.2.1 on 2019-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_is_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfrequency',
            name='normal_drink',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userfrequency',
            name='special_drink',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userfrequency',
            name='user_number',
            field=models.PositiveIntegerField(),
        ),
    ]
