# Generated by Django 2.2.1 on 2019-08-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('ORDER_SEND', 'Order Send'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELED', 'Order Canceled'), ('PRODUCT_READY', 'Product Ready')], default='PAID', max_length=20)),
                ('takeout', models.CharField(choices=[('EAT_IN', 'Eat In'), ('TAKE_OUT', 'Take Out')], max_length=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'orders_products',
            },
        ),
    ]
