# Generated by Django 2.2.1 on 2019-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('ORDER_SEND', 'Order Send'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELED', 'Order Canceled'), ('PRODUCT_READY', 'Product Ready')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='takeout',
            field=models.CharField(choices=[('EAT_IN', 'Eat In'), ('TAKE_OUT', 'Take Out')], max_length=10),
        ),
    ]
