# Generated by Django 2.2.1 on 2019-06-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
    ]
