# Generated by Django 2.2.1 on 2019-06-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190622_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문들'},
        ),
    ]
