# Generated by Django 2.2.1 on 2019-07-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
